updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,14 +9,15 @@ jobs:
     executor: python/default
     steps:
       - checkout
-      - name: Select branch to merge into
-        run: |
-          if [[ "$CIRCLE_BRANCH" == /*base-image ]]; then
-            if [[ $BASE_BRANCH_NAME != "base" ]]; then
-              echo "error: Base branches can only be merged into the base branch.!!!!"
-              exit 1
+        run:
+          name: Select branch to merge into
+          command: |
+            if [[ "$CIRCLE_BRANCH" == /*base-image ]]; then
+              if [[ $BASE_BRANCH_NAME != "base" ]]; then
+                echo "error: Base branches can only be merged into the base branch.!!!!"
+                exit 1
+              fi
             fi
-          fi
   linting:
     executor: python/default
     resource_class: small
