updated

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,9 +11,11 @@ jobs:
       - checkout
       - name: Select branch to merge into
         run: |
-          if [[ $PR_BRANCH_NAME == /*base-branch && $BASE_BRANCH_NAME != "base" ]]; then
-            echo "error: Base branches can only be merged into the base branch.!!!!"
-            exit 1
+          if [[ "$CIRCLE_BRANCH" == /*base-image ]]; then
+            if [[ $BASE_BRANCH_NAME != "base" ]]; then
+              echo "error: Base branches can only be merged into the base branch.!!!!"
+              exit 1
+            fi
           fi
   linting:
     executor: python/default
